import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import Login from "./components/login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const loginFunction = async (user: string) => {
    "use server";

    cookies().set("login", user);
    return true;
  };

  const login = cookies().get("login");

  return (
    <html lang="en">
      <body className={inter.className}>
        {login ? <div>{children}</div> : <Login setLogin={loginFunction} />}
      </body>
    </html>
  );
}
